# This workflow scans commits and pull requests for dependency changes
#   and will raise an error if any new dependencies have existing
#   vulnerabilities. The action is supported by an API endpoint that
#   diffs the dependencies between any two revisions. For more
#   information see:
#   https://github.com/marketplace/actions/dependency-review

name: dependency-review

on:
  pull_request:
    branches: [ main ]

jobs:
  dependency-review:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Dependency Review
      uses: actions/dependency-review-action@v3
